# Generated by Django 5.2 on 2025-11-06 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('galeria', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='fotografia',
            name='categoria',
            field=models.CharField(choices=[('PLANETA', 'Planeta'), ('GALÁXIA', 'Galáxia'), ('NEBULOSA', 'Nebulosa'), ('ESTRELA', 'Estrela')], default='', max_length=100),
        ),
    ]
