# Generated by Django 5.2 on 2025-11-11 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('galeria', '0004_fotografia_data_fotografia_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fotografia',
            name='categoria',
            field=models.CharField(choices=[('GALÁXIA', 'Galáxia'), ('PLANETA', 'Planeta'), ('ESTRELA', 'Estrela'), ('NEBULOSA', 'Nebulosa')], default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='fotografia',
            name='foto',
            field=models.ImageField(blank=True, upload_to='fotos/%Y%m%d/'),
        ),
    ]
